services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/xvr/docker/homarr/configs:/app/data/configs
      - /home/xvr/docker/homarr/icons:/app/public/icons
      - /home/xvr/docker/homarr/data:/data
    ports:
      - '7575:7575' 
